blank_issues_enabled: false
contact_links:
  - name: Github discussions
    url: https://github.com/deforum-art/sd-webui-modelscope-text2video/discussions
    about: Please ask and answer questions here as well as share your art. But if you want to complain about something, don't try to circumvent issue filling by starting a discussion here 🙃
